language: node_js
sudo: false
node_js:
  - '4.4.5' # Last LTS
  - '5'
  - '5.11.1' # Last v5.x build
  - '6'
  - 'node' # Latest

cache:
  directories:
    - node_modules
    - typings
install:
  # Disable progress bar as it slows things down
  - npm config set progress false
  # Install dependencies
  - npm run setup

script:
  - npm test